=== ittimeline/java/java-foundational/src/main/resources/order.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
 xmlns:xs="http://www.w3.org/2001/XMLSchema" 表示标准命名空间 每个Schema约束都会包含一个标准命名空间
  targetNamespace="www.ittimeline.net" 表示目标命名空间(自定义命名空间)

-->
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://www.ittimeline.net"
        elementFormDefault="qualified"
>

<!--    将Schema约束绑定到目标命名空间-->

<!--    定义Schema约束-->
    <!--
        orders是xml文件的根标签

    -->
    <xs:element name="orders">
        <!--   complexType表示orders标签是复杂标签
                orders标签是复杂标签，即可以包含其他子标签
             -->
        <xs:complexType>
            <!--
                sequence表示按照顺序出现
                  maxOccurs 表示最大出现次数
                  minOccurs 表示最小出现次数
              -->
            <xs:sequence maxOccurs="3" minOccurs="1">
                <!--                orders标签下的子标签是order-->
                <xs:element name="order">
                    <!--                    order标签也是复杂标签-->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:unsignedInt"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="bookTime" type="xs:dateTime"/>
                            <xs:element name="amount" type="xs:double"/>
                        </xs:sequence>

                        <!--
                        order标签必须包含orderId属性，该属性类型是无符号整数，而且必须定义
                        required表示必须定义
                         optional表示可选的
                        -->
                        <xs:attribute name="orderId" type="xs:unsignedInt" use="required"/>


                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

    </xs:element>


</xs:schema>

=== ittimeline/java/java-foundational/src/main/resources/order-alias.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--Schema约束的使用-->
<orders
        xmlns:ittimline="https://www.ittimeline.net"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.ittimeline.net  order.xsd"
>
    <ittimline:order orderId="10001">
        <id>10001</id>
        <address>上海市黄浦区</address>
        <bookTime>2021-06-20T08:00:00</bookTime>
        <amount>8888.88</amount>
    </ittimline:order>

    <ittimline:order orderId="10002">
        <id>10002</id>
        <address>上海市长宁区</address>
        <bookTime>2021-06-20T08:00:00</bookTime>
        <amount>8888.88</amount>
    </ittimline:order>


    <ittimline:order orderId="10003">
        <id>10003</id>
        <address>上海市静安区</address>
        <bookTime>2021-06-20T08:00:00</bookTime>
        <amount>8888.88</amount>
    </ittimline:order>
</orders>

=== ittimeline/java/java-foundational/src/main/resources/order.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--Schema约束的使用-->
<orders
        xmlns="https://www.ittimeline.net"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.ittimeline.net  order.xsd"
>
    <order orderId="10001">
        <id>10001</id>
        <address>上海市黄浦区</address>
        <bookTime>2021-06-20T08:00:00</bookTime>
        <amount>8888.88</amount>
    </order>

    <order orderId="10002">
        <id>10002</id>
        <address>上海市长宁区</address>
        <bookTime>2021-06-20T08:00:00</bookTime>
        <amount>8888.88</amount>
    </order>


    <order orderId="10003">
        <id>10003</id>
        <address>上海市静安区</address>
        <bookTime>2021-06-20T08:00:00</bookTime>
        <amount>8888.88</amount>
    </order>
</orders>
